### PR TITLE
[ISSUE # 250 & 249 & 248] Support sum&min&max function in WindowStream 

### PR DESCRIPTION
**Pull request by joeCarf**
issue: https://github.com/apache/rocketmq-streams/issues/250
issue : https://github.com/apache/rocketmq-streams/issues/249
issue: https://github.com/apache/rocketmq-streams/issues/248

### CODE REVIEW

**Comment by ni-ze** [comment]
can you give the origin data and result of examples?
@joeCarf

**Comment by joeCarf** [comment]
Input and outputs of examples:
Input: 
input


WindowSum output: 
windowSum

WindowMin output:
windowMin

WindowMax output:
windowMax

**Comment by ni-ze** [comment]
@joeCarf the result is correct. please don't use event_time in example, because if your time not change in data. The data will be discarded when you send at second time.

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `enhancement` | Status: **Evaluated**

Feature request to support `sum`, `min`, and `max` aggregate functions in WindowStream processing. Related to issues #250, #249, #248.

**Feasibility:** feasible
**Scope:** `WindowStream` API, aggregate function implementations
**Compatibility:** additive API, backward compatible

Note: This issue is from early 2023. Please verify if these functions have been implemented in recent releases.

---
*Automated evaluation by github-manager-bot*

**Pull request merged**
