### PR TITLE
Use shade plugin to hide dependencies

### LINKED ISSUE #165: There is dependency conflict if application and RocketMQ Streams has same dependency.
There is dependency conflict if application and RocketMQ Streams has same dependency.
RocketMQ Streams as a SDK, which is dependent by application, should shade it's dependency to avoid conflict.

### PR DESCRIPTION
**Pull request by totalo**
Fixed #165

### CODE REVIEW

**Comment by ni-ze** [comment]
@totalo Great patch!

**Comment by ni-ze** [comment]
However this pr do not resolve dependency conflicts, because dependency of RocketMQ-Streams can be depend by application which depend on  RocketMQ-Streams.

**Comment by totalo** [comment]
> However this pr do not resolve dependency conflicts, because dependency of RocketMQ-Streams can be depend by application which depend on RocketMQ-Streams.

ok, i'll check it.

**Comment by totalo** [comment]
hi @ni-ze, plz check it.thanks

**Comment by ni-ze** [comment]
> hi @ni-ze, plz check it.thanks

I check it,example and application depend on rocketmq-client works well.

**Review by ShannonDing — APPROVED** [review]

**Comment by totalo** [comment]
> > hi @ni-ze, plz check it.thanks
> 
> I check it,example and application depend on rocketmq-client works well.

Hi@ni-ze, is there any problem with this?

**Pull request merged**
